import streamlit as st
import socket
import requests
from concurrent.futures import ThreadPoolExecutor
from fpdf import FPDF

# --- Page Config & Styling ---
st.set_page_config(page_title="Sentinel-X Pro", layout="wide")

st.markdown("""
    <style>
    .main { background-color: #0e1117; color: #00ff41; }
    .stButton>button { background-color: #00ff41; color: black; font-weight: bold; width: 100%; }
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #0e1117;
        color: #00ff41;
        text-align: center;
        padding: 10px;
        font-family: 'Courier New', Courier, monospace;
        font-size: 14px;
        border-top: 1px solid #00ff41;
    }
    </style>
    """, unsafe_allow_html=True)

# --- PDF Generation Function ---
def create_pdf(scan_results, target):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Sentinel-X: Recon Report", ln=True, align='C')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Target: {target}", ln=True, align='L')
    pdf.cell(200, 10, txt="---------------------------------------", ln=True, align='L')
    
    for res in scan_results:
        text = f"Port: {res['Port']} | Status: {res['Status']} | Service: {res['Service Info']}"
        pdf.cell(200, 10, txt=text, ln=True, align='L')
    
    pdf.ln(10)
    pdf.cell(200, 10, txt="Generated by Sentinel-X | (c) 2026 Satyam", ln=True, align='C')
    return pdf.output(dest='S').encode('latin-1')

# --- Main App Logic ---
st.title("🛡️ Sentinel-X: Cyber Recon Tool")

option = st.sidebar.selectbox("Select Module", ["Dashboard", "IP Scanner", "Port Scanner (Turbo)"])

if option == "Dashboard":
    st.subheader("System Status: Online")
    st.info("Sentinel-X is ready for reconnaissance. Choose a module from the sidebar.")

elif option == "IP Scanner":
    st.subheader("🌐 IP/Domain Reconnaissance")
    target = st.text_input("Enter Domain/IP")
    if st.button("Scan Target"):
        try:
            ip_addr = socket.gethostbyname(target)
            st.success(f"Target IP: {ip_addr}")
            response = requests.get(f"http://ip-api.com/json/{ip_addr}").json()
            st.json(response)
        except Exception as e:
            st.error(f"Error: {e}")

elif option == "Port Scanner (Turbo)":
    st.subheader("🔌 Multi-Threaded Port Scanner")
    target_ip = st.text_input("Target IP/Domain")
    port_range = st.slider("Port Range", 1, 1000, (20, 443))
    
    def scan_port(port):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(0.3)
        result = s.connect_ex((target_ip, port))
        if result == 0:
            try:
                banner = s.recv(1024).decode().strip()
                return (port, "OPEN", banner if banner else "No Banner")
            except:
                return (port, "OPEN", "Unknown Service")
        s.close()
        return None

    if st.button("Start Turbo Scan"):
        st.write(f"Scanning {target_ip}...")
        found_ports = []
        with ThreadPoolExecutor(max_workers=50) as executor:
            ports = range(port_range[0], port_range[1] + 1)
            results = list(executor.map(scan_port, ports))
            for res in results:
                if res:
                    found_ports.append(res)
        
        # Save results in session state so it doesn't disappear
        st.session_state['scan_results'] = found_ports

    # Check if results exist in session state to avoid NameError
    if 'scan_results' in st.session_state and st.session_state['scan_results']:
        results_data = [{"Port": p[0], "Status": p[1], "Service Info": p[2]} for p in st.session_state['scan_results']]
        st.table(results_data)
        
        pdf_bytes = create_pdf(results_data, target_ip)
        st.download_button(
            label="📥 Download Scan Report (PDF)",
            data=pdf_bytes,
            file_name=f"SentinelX_{target_ip}.pdf",
            mime="application/pdf"
        )
    elif 'scan_results' in st.session_state:
        st.warning("No open ports found.")

# --- Permanent Footer ---
st.markdown("""
    <div class="footer">
        <p>© 2026 Satyam | Sentinel-X Cyber Recon Tool | All Rights Reserved</p>
    </div>
    """, unsafe_allow_html=True)
